# Generated by Django 4.2.6 on 2023-11-02 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_logisticinfo_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='upldfile/', verbose_name='Текстовий файл')),
                ('text_date', models.DateTimeField(verbose_name='Дата створення файлу')),
            ],
        ),
    ]
