# Generated by Django 4.2.6 on 2023-11-05 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_textfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textfile',
            name='file',
            field=models.FileField(null=True, upload_to='', verbose_name='Текстовий файл'),
        ),
    ]
